### PR TITLE
Show branches created at runtime

### LINKED ISSUE #203: Branches created into the behavior tree at runtime do not show up in the debugger
Godot version: 4.1.0

**Describe the bug**
Creating a "branch" into the behavior tree at runtime will not make it appear in the debugger.

**To Reproduce**
Use the minimal project I created to observe the bug.
1) Start the project
2) Observe that a debug print is being made every second
3) Open beehave debugger and see that the branch is not shown there

**Expected behavior**
Branches created at runtime should show up in the debugger

**Screenshots**
Screenshot 2023-07-11 at 21 28 30

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1
 - Run project from godot
 - Version 2.7.4

**Additional context**
Minimal project file.
[BeehaveBranchBug.zip](https://github.com/bitbrain/beehave/files/12017904/BeehaveBranchBug.zip)

### PR DESCRIPTION
**Pull request by DarkMessiah**
## Addressed issues

Fixes https://github.com/bitbrain/beehave/issues/203

## Screenshots

https://github.com/bitbrain/beehave/assets/1756388/fad62260-a6b3-4d0c-89bb-736791edb0c7

### CODE REVIEW

**Comment by bitbrain** [comment]
@DarkMessiah As discussed, this solution may not consider children getting added further down in the tree but only to the root level. I will do further testing on this to verify.

We may also want to add some rudimentary unit tests for this which also would close https://github.com/bitbrain/beehave/issues/188

Refer to the [GDUnit docs](https://mikeschulze.github.io/gdUnit3/advanced_testing/sceneRunner/) as well as [the unit testing docs](https://bitbra.in/beehave/#/contribute?id=%f0%9f%a7%aa-unit-testing) on how to do that.

**Comment by hunttis** [comment]
I can confirm that this does not consider children getting added further into the tree. My Behavior Tree structure is such that I have a movementTree, where the moveBehavior gets children based on the role of the character, let's say "leaderMovement" and "followerMovement". These do not show up.

**Comment by hunttis** [comment]
This is still relevant for me. I've put the project using beehave on pause for the time being. I've tried looking at the code in this PR, but I don't really understand enough of what's happening to fix it myself.

If you could give me a general idea on what needs to happen there, I can try to fix it.

Also, if it helps, I can make another minimal project that replicates this issue.

**Comment by bitbrain** [comment]
Closing this, as this has been implemented by #301 instead.

**Pull request closed without merging**
