### PR TITLE
A little nicer debugging

### PR DESCRIPTION
**Pull request by tavurth**
## Description

As discussed in the other PR `delta` is not needed in the `Blackboard`

I also added `microseconds` to the custom monitor, as the units were a little confusing to me before and I had to look it up.

## Addressed issues

N/A

## Screenshots

Screenshot 2023-04-25 at 18 46 32

### CODE REVIEW

**Comment by bitbrain** [comment]
Looks great - a little nitpick: it might be better to convert to milliseconds (not microseconds) as frame budgets are usually reasoned with in milliseconds. Ideally, Godot itself should give you the option to choose the time format but unfortunately it does not support that in the editor...

**Comment by tavurth** [comment]
Hmm while true, godot expects a float or an integer.

Float cannot be rounded to a nice even number 🤔

**Comment by tavurth** [comment]
Attempting to round ends up like this:

Screenshot 2023-04-25 at 21 14 25

Leaving unrounded ends up like this:
Screenshot 2023-04-25 at 21 15 05

**Comment by bitbrain** [comment]
Yuck! Fine, let us merge this for now and see how we can perhaps improve Godot Engine itself to handle this better.

**Review by bitbrain — APPROVED** [review]

**Pull request merged**
