### PR TITLE
Add a .gitattributes file #22

### PR DESCRIPTION
**Pull request by kaluluosi**
## Description
This PR include these:

1. Add a .gitattributes file #22 (see godot docs [Recommendations](https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html))
Exclude other file/folder except addons.

Use this command line to export zip:
> git archive --format zip --output ./beehave.zip godot-3.x

image

Test import asset
image

2. Recreate project.godot file. 
3. Set BeehaveTree.gd class icon
image
4. Project Splash Screen.

Now you can open and develop this project as godot project, and it will export a pure plugin zip for Godot Asset Library to download.
It make good experience for developer.

This PR desn't modified addons/beehave code.

## Addressed issues

- Add a .gitattributes file #22 

## Screenshots

Snipaste_2022-08-31_16-26-50
Snipaste_2022-08-31_16-25-56
Snipaste_2022-08-31_17-25-45

## Checklist

- [x] changes performed compatible with Godot 3.x
- [ ] changes performed compatible with Godot 4.x (raised in a separate PR against the `2.x` branch in case the change is not compatible with Godot 3.x like specific syntax)
- [ ] Unit tests (Godot 4 only after https://github.com/bitbrain/beehave/issues/2 is done)

### CODE REVIEW

**Comment by bitbrain** [comment]
@kaluluosi what was the idea behind removing the `.import` files? We might want to bring them back and revert the change within `.gitignore`. They may contain custom changes done via the editor itself (as the editor persist import settings as part of `.import` and not `.tscn`)

**Review by bitbrain — CHANGES_REQUESTED** [review]
Restore .import files

**Comment by kaluluosi** [comment]
> Restore .import files

Restored .import files.

And make .gitattributes same as godot official recommendations

image

Test 

image

**Review by bitbrain — APPROVED** [review]

**Comment by bitbrain** [comment]
@kaluluosi could we raise a similar PR against the `godot-4.x` branch? That'd be highly appreciated!

**Comment by kaluluosi** [comment]
> @kaluluosi could we raise a similar PR against the `godot-4.x` branch? That'd be highly appreciated!

I will do it later.  I didn't have godot 4.x yet, I must download one and test for 4.0 version.

**Comment by bitbrain** [comment]
@kaluluosi thank you! Also make sure to create your branch from the existing godot-4.x branch, as the current main branch (godot-3.x) is incompatible.

**Comment by kaluluosi** [comment]
> 

got it. 🤝

**Pull request merged**
